### ISSUE TITLE
TypeError $.useref.assets is not a function

### ISSUE THREAD

**Issue by linus-amg** [abiee/es6-marionette#6]
hi, i did the following:
- git clone https://github.com/abiee/es6-marionette
- cd es6-marionette
- gulp build

and got this error: 

``` sh
~/lab/es6-marionette master 2m 47s
❯ gulp build
[09:47:50] Using gulpfile ~/lab/es6-marionette/gulpfile.js
[09:47:50] Starting 'jshint'...
[09:47:50] Starting 'browserify:dist'...
[09:47:50] Starting 'styles'...
[09:47:51] Starting 'images'...
[09:47:51] Starting 'fonts'...
[09:47:51] Starting 'extras'...
[09:47:51] Finished 'images' after 483 ms
[09:47:51] Finished 'jshint' after 1.49 s
[09:47:51] Finished 'extras' after 174 ms
[09:47:51] Finished 'styles' after 1.09 s
[09:47:51] Starting 'html'...
[09:47:51] 'html' errored after 17 ms
[09:47:51] TypeError: $.useref.assets is not a function
    at Gulp.<anonymous> (/Users/lgubenis/lab/es6-marionette/gulpfile.js:111:25)
    at module.exports (/Users/lgubenis/lab/es6-marionette/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/lgubenis/lab/es6-marionette/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/lgubenis/lab/es6-marionette/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /Users/lgubenis/lab/es6-marionette/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/Users/lgubenis/lab/es6-marionette/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/lgubenis/lab/es6-marionette/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/lgubenis/lab/es6-marionette/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at PassThrough.onend (/Users/lgubenis/lab/es6-marionette/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
    at emitNone (events.js:72:20)
    at PassThrough.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
[09:47:54] Finished 'fonts' after 2.82 s
[09:48:00] Finished 'browserify:dist' after 9.95 s
```

**Comment by linus-amg** [comment]
node 5.3.0

**Comment by abiee** [comment]
I just upgrade the dependencies, can you check again?
